name: Build and Push CUDA Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch: # allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/go /opt/hostedtoolcache/CodeQL
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./comfyui-without-flux
          file: ./comfyui-without-flux/Dockerfile
          push: true
          tags: gasparuff/comfyui-without-flux:v1.0.0
          cache-to: type=inline
          cache-from: type=registry,ref=gasparuff/comfyui-without-flux:cache
          outputs: type=image,push=true  # 🧠 This avoids local export
          platforms: linux/amd64
